int getRank(double **matrix, int rows, int cols);
void getProduct(double **aMatrix, double **bMatrix, int aRows, int aCols, int bRows, int bCols);
void getSum(double **aMatrix, double **bMatrix, double **cMatrix, int rows, int cols);
void getDifference(double **aMatrix, double **bMatrix, double **cMatrix, int rows, int cols);
void getREF(double **matrix, int rows, int cols);
void getTranspose(double **matrix, int rows, int cols);
void getDeterminant(double **matrix, int rows, int cols);
void getInverse(double **matrix, int rows, int cols);
void swap(double **matrix, int a, int b, int rows, int cols);
void printMatrix(double **matrix, int rows, int cols);